# 应用名称
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: mysql
  application:
  name: runner-test
  servlet:
    multipart:
      max-file-size: 100MB
  security:
    user:
      name: ja22
      password: 123
  redis:
    port: 6379
    host: 127.0.0.1
    database: 4
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
#MYBATIS
mybatis:
  mapper-locations: classpath:mapper/*.xml


# 应用服务 WEB 访问端口
server:
  port: 8080
logging:
  config: classpath:logback-spring.xml



